version: "3.7"
services:
  client:
    build:
      context: ./web
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    working_dir: /web/src/app
    volumes:
      - ./web:/web/src/app
    entrypoint: ["npm", "start"]
    links:
      - api
    networks:
      - webappnetwork
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3333:3333"
    volumes:
      - ./backend:/backend
      - /backend/node_modules
    depends_on:
      - mongodb
    networks:
      - webappnetwork
  mongodb:
    image: mongo
    restart: always
    container_name: mongodb
    volumes:
      - ./data:/data/db
    ports:
      - 27018:27017
    command: mongod --noauth
    networks:
      - webappnetwork
networks:
  webappnetwork:
    driver: bridge
