version: "3"
services:
  client:
    build: ./web
    entrypoint: ./web/.docker/entrypoint.sh
    container_name: frontend-clubpetro
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./web:/home/node/app
    links:
      - api
    networks:
      - webappnetwork
  api:
    build: ./backend
    entrypoint: ./backend/.docker/entrypoint.sh
    container_name: backend-clubpetro
    ports:
      - "3333:3333"
    volumes:
      - ./backend:/home/node/app
    depends_on:
      - mongodb
    networks:
      - webappnetwork
  mongodb:
    image: mongo
    restart: always
    container_name: mongodb
    volumes:
      - ./.docker/dbdata:/data/db
    ports:
      - 27017:27017
    command: mongod --noauth
    networks:
      - webappnetwork
networks:
  webappnetwork:
    driver: bridge
