version: '3.7'
services:
  server:
    container_name: clubpetro-backend-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '3333:3333'
    environment:
      - NODE_ENV=development
      - DB_URL=mongodb://db_mongo
    depends_on:
      - db
    links:
      - db

  db:
    image: mongo
    container_name: db_mongo
    volumes:
      - mongodata:/data/db
    ports:
      - '27017:27017'
    volumes:
      - ./data/db:/data/db
