version: '3'
services:
  back_app:
    depends_on:
      - db
    restart: always
    build: .
    ports:
      - '8080:3333'
    environment:
      - DB_URL=mongodb://db_mongo
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    links:
      - db
    networks:
      - webnet

  db:
    image: mongo
    container_name: db_mongo
    volumes:
      - mongodata:/data/db
    networks:
      - webnet
    ports:
      - '27018:27017'

volumes:
  mongodata:

networks:
  webnet:
